### ISSUE TITLE
Exporter UI - Search doesn't search

### ISSUE THREAD

**Issue by BrandonSharratt** [bcgov/OCWA#42]
## User Story
**As a** _user_,<br>
**I want** _to search for requests_<br>
**so that** _I can find my request easily_.

## Test Case

# ENV
`DEV`, `TEST`

# TESTCASE
1) Log in to the export interface with more than 1 page of requests (Dev is perfect)
2) Search for a request that is NOT on page 1 (bTest in Dev)
3) See either no results or a few results
4) Go to the next page and perform the same search, note different results

# EXPECTED
I see all of the results regardless of page

# ACTUAL
I only see the results from the page I am on

Note: I am not opposed to having a page filter, but we should also have a search functionality.

**Comment by pripley123** [comment]
Testing failed in test environment (used the search term "word" (there are multiple requests on page 2 with that word in them).  Moving back to backlog.

**Comment by Jonesy** [comment]
@BrandonSharratt Paul and I looked into this and it looks like the problem is that the `name` parameter will only return a hit if it's an exact string match with a request in the database. I propose we keep this functionality on the `name` parameter so I can check if a request name is available, but add a `search` parameter that does more of a traditional search that returns possible matches.

**Comment by BrandonSharratt** [comment]
I have added search functionality to the existing endpoint.

if you append a * character to your search criteria (note append) it will do an insensitive regex search (contains) so it effectively applies a * to both sides of your search. If you do not append the * the functionality will be as it currently is.

Therefore when searching you could append a * for the user and not when you want to get a specific request by name

**Comment by pripley123** [comment]
This one is going to be inconvenient to verify in the test environment since we've cleared out all old requests.  That said, search did appear to behave as expected (with only one page of requests).  I did notice if you add a "*" to the front of a query you get some weird behaviour - a blank screen - however, not something we need to resolve for MVP.
